plugins {
    id 'com.android.application'
}

android {
    namespace 'at.spanwerk.maschinenstundensatz'
    compileSdk 34

    defaultConfig {
        applicationId "at.spanwerk.maschinenstundensatz"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
